### ISSUE TITLE
7-zip variable wrong

### ISSUE THREAD

**Issue by ericvanboven** [MSEndpointMgr/ModernDriverManagement#9]
You using $DriverPackageCompressedContent but above that the variable is $DriverPackageCompressedFile. You might of forgot to combine location and zip file into one variable to be used.

**Comment by merlinfrombelgium** [comment]
@ericvanboven You're right. `$DriverPackageCompressedContent` is never defined and must have been missed during rename action.

@NickolajA I suggest to use PSScriptAnalyzer to identify these issues. Helped me spot many self-created issues many times! ☺

**Comment by NickolajA** [comment]
Fixed in 4.0.1 that was just committed.

**Comment by merlinfrombelgium** [comment]
#14 I spoke too soon...

**Comment by N8-EndpointMgr** [comment]
The issue still exists in the Legacy script in the latest revision released. @NickolajA @merlinfrombelgium
